version: '3.5'
services:

  server:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
    volumes:
      - ./config/server.properties:/data/server.properties
